# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 888)
        MainWindow.setMinimumSize(QtCore.QSize(1250, 850))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-image: url(:/images/covid-19-2-800x500-1.jpg);\n"
"background-image: url(:/images/coronavirus-image-1_1200xx2121-1193-0-111.jpg);\n"
"background-repeat: repeat-x ;\n"
"background-color: rgb(102, 0, 0);")
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 153, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(804, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 196, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 0, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 3, 1, 1)
        self.MapGraphButton = QtWidgets.QPushButton(self.tab_6)
        self.MapGraphButton.setMinimumSize(QtCore.QSize(400, 300))
        self.MapGraphButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MapGraphButton.setStyleSheet("background-image: url(:/images/map.JPG);")
        self.MapGraphButton.setText("")
        self.MapGraphButton.setObjectName("MapGraphButton")
        self.gridLayout_4.addWidget(self.MapGraphButton, 0, 3, 1, 1)
        self.SortedChartButton = QtWidgets.QPushButton(self.tab_6)
        self.SortedChartButton.setMinimumSize(QtCore.QSize(400, 300))
        self.SortedChartButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SortedChartButton.setStyleSheet("background-image: url(:/images/Ranks.JPG);")
        self.SortedChartButton.setText("")
        self.SortedChartButton.setObjectName("SortedChartButton")
        self.gridLayout_4.addWidget(self.SortedChartButton, 0, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 1, 1, 1)
        self.BubbleChartButton = QtWidgets.QPushButton(self.tab_6)
        self.BubbleChartButton.setMinimumSize(QtCore.QSize(400, 300))
        self.BubbleChartButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BubbleChartButton.setStyleSheet("background-image: url(:/images/bubble.JPG);")
        self.BubbleChartButton.setText("")
        self.BubbleChartButton.setObjectName("BubbleChartButton")
        self.gridLayout_4.addWidget(self.BubbleChartButton, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 3, 0, 1, 2)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.popView = QtWebEngineWidgets.QWebEngineView(self.tab_7)
        self.popView.setUrl(QtCore.QUrl("about:blank"))
        self.popView.setObjectName("popView")
        self.gridLayout_5.addWidget(self.popView, 0, 0, 1, 1)
        self.popBtn = QtWidgets.QPushButton(self.tab_7)
        self.popBtn.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.popBtn.setObjectName("popBtn")
        self.gridLayout_5.addWidget(self.popBtn, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Menu"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Data Analysis"))
        self.label.setText(_translate("MainWindow", "Data Analysis"))
        self.label_9.setText(_translate("MainWindow", "                Sorted Chart"))
        self.label_8.setText(_translate("MainWindow", "                Map Graph"))
        self.label_10.setText(_translate("MainWindow", "                Bubble Chart"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "COVID-19"))
        self.popBtn.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Page"))

from PyQt5 import QtWebEngineWidgets
import sourcc_rc
